Update GHAS.yml

diff --git a/.github/workflows/GHAS.yml b/.github/workflows/GHAS.yml
--- a/.github/workflows/GHAS.yml
+++ b/.github/workflows/GHAS.yml
@@ -26,21 +26,25 @@ jobs:
 
       - name: Perform CodeQL Analysis
         uses: github/codeql-action/analyze@v3
-
+        
       # --- Semgrep Analysis ---
       - name: Run Semgrep
         uses: returntocorp/semgrep-action@fcd5ab7459e8d91cb1777481980d1b18b4fc6735
         with:
           config: auto
           sarif: true
-          include-git-ignored: true
-          max-target-bytes: 5000000
-          no-ignore: true
           output: semgrep.sarif
-          continue-on-error: true  
+
+      - name: Check if SARIF file exists
+        run: |
+          if [ -f semgrep.sarif ]; then
+            echo "SARIF file found."
+          else
+            echo "SARIF file missing!"
+            exit 1
+          fi
 
       - name: Upload SARIF to GitHub Code Scanning
-        if: always()  
         uses: github/codeql-action/upload-sarif@v3
         with:
           sarif_file: semgrep.sarif
